### PR TITLE
integrate captain hook and prettier; enhance README

### PR DESCRIPTION
**Pull request by cpfpolkehn**
@Andreas-Halemba

1. left out commit message validation due to your usage of emoticons. We could however construct a regex for that case as well if we agree upon the used emoticons and the rest of the structure, I'd suggest we use https://www.conventionalcommits.org/en/v1.0.0/ here as well.
2. Some of the tests fail for me at this point, you might want to take a look at these: 
grafik

3. Prettier is integrated as well and all "issues" are fixed

### CODE REVIEW

**Comment by cpfpolkehn** [comment]
@Andreas-Halemba added another commit that fixes the tests: https://github.com/Andreas-Halemba/livewire-planning-poker/pull/5/commits/396b3fa958ce018d42d3862ad0538e337cfe7e18

**Comment by Andreas-Halemba** [comment]
Can we agree on single quotes in JavaScript? Or is there any reason for not to? @cpfpolkehn

**Comment by cpfpolkehn** [comment]
@Andreas-Halemba fixed, forgot to integrate `.prettierrc.json` which defines single quotes to be used -> fixed

**Review by Andreas-Halemba — APPROVED** [review]
looks good to me

**Pull request merged**
